/**
 * ╔══════════════════════════════════════════════════════════════╗
 * ║  FRAMEWORK STYLES — Global UI style registry.               ║
 * ║  Every component style variant lives here.                  ║
 * ║  Admin picks a style → stored in siteConfig → applied live. ║
 * ╚══════════════════════════════════════════════════════════════╝
 */

export const MENU_STYLES = [
  { id: 'cyber',    label: 'Cyber',     desc: 'Green glow, mono font, dark bg',   icon: '⬡' },
  { id: 'glass',    label: 'Glass',     desc: 'Frosted blur, translucent panel',  icon: '◻' },
  { id: 'terminal', label: 'Terminal',  desc: 'Green-on-black, CLI aesthetic',    icon: '>_' },
  { id: 'minimal',  label: 'Minimal',   desc: 'Clean, no glow, subtle shadow',    icon: '—' },
  { id: 'neon',     label: 'Neon',      desc: 'Vivid colors, bright borders',     icon: '✴' },
  { id: 'floating', label: 'Floating',  desc: 'Large radius, deep shadows',       icon: '◎' },
  { id: 'command',  label: 'Command',   desc: 'Palette layout with shortcuts',    icon: '⌘' },
  { id: 'rail',     label: 'Rail',      desc: 'Left icon rail with detail pane',   icon: '▌' },
  { id: 'paper',    label: 'Paper',     desc: 'Light document popover',           icon: '□' },
  { id: 'arcade',   label: 'Arcade',    desc: 'Chunky pixel menu states',         icon: '▣' },
  { id: 'holo',     label: 'Holo',      desc: 'Holographic layered glow',         icon: '❋' },
  { id: 'matrix',   label: 'Matrix',    desc: 'Phosphor rain green monochrome',   icon: '🌧' },
]

export const NOTIFY_STYLES = [
  { id: 'cyber',    label: 'Cyber',     desc: 'Accent bar, scanline, mono',       icon: '⬡' },
  { id: 'pill',     label: 'Pill',      desc: 'Fully rounded, compact badge',     icon: '◉' },
  { id: 'minimal',  label: 'Minimal',   desc: 'Clean card, thin border',          icon: '—' },
  { id: 'terminal', label: 'Terminal',  desc: '[TYPE] message format',            icon: '>_' },
  { id: 'glass',    label: 'Glass',     desc: 'Frosted blur, soft glow',          icon: '◻' },
  { id: 'banner',   label: 'Banner',    desc: 'Full-width top strip',             icon: '▬' },
  { id: 'float',    label: 'Float',     desc: 'Rich card with timestamp',         icon: '◈' },
  { id: 'glitch',   label: 'Glitch',    desc: 'High-impact system alert',         icon: '!' },
  { id: 'inbox',    label: 'Inbox',     desc: 'Stacked notification feed',        icon: '≡' },
  { id: 'hud',      label: 'HUD',       desc: 'Compact corner telemetry',         icon: '◇' },
  { id: 'holo',     label: 'Holo',      desc: 'Holographic layered glow',         icon: '❋' },
  { id: 'chip',     label: 'Chip',      desc: 'Compact telemetry chip',           icon: '●' },
]

export const DIALOG_STYLES = [
  { id: 'cyber',    label: 'Cyber',     desc: 'Corner accents, gradient top bar', icon: '⬡' },
  { id: 'glass',    label: 'Glass',     desc: 'Frosted backdrop, blur',           icon: '◻' },
  { id: 'terminal', label: 'Terminal',  desc: 'Window chrome with traffic dots',  icon: '>_' },
  { id: 'sheet',    label: 'Sheet',     desc: 'Slides up from bottom',            icon: '⬆' },
  { id: 'minimal',  label: 'Minimal',   desc: 'Clean centered card',              icon: '—' },
  { id: 'brutal',   label: 'Brutalist', desc: 'Thick border, high contrast',      icon: '■' },
  { id: 'command',  label: 'Command',   desc: 'Search palette confirmation',      icon: '⌘' },
  { id: 'split',    label: 'Split',     desc: 'Icon panel beside copy',           icon: '▥' },
  { id: 'drawer',   label: 'Drawer',    desc: 'Right-side inspector panel',       icon: '▐' },
  { id: 'paper',    label: 'Paper',     desc: 'Editorial document modal',         icon: '□' },
  { id: 'holo',     label: 'Holo',      desc: 'Holographic corner brackets',      icon: '❋' },
  { id: 'crt',      label: 'CRT',       desc: 'Green phosphor scanline terminal', icon: '🖥' },
]

export const INPUT_STYLES = [
  { id: 'cyber',    label: 'Cyber',    desc: 'Angular fields with scan accent',    icon: '▱' },
  { id: 'glass',    label: 'Glass',    desc: 'Blurred translucent input panels',   icon: '◻' },
  { id: 'terminal', label: 'Terminal', desc: 'CLI prompt fields with caret',       icon: '>_' },
  { id: 'minimal',  label: 'Minimal',  desc: 'Quiet underline and soft focus',     icon: '—' },
  { id: 'brutal',   label: 'Brutal',   desc: 'Thick black border and hard shadow', icon: '■' },
  { id: 'paper',    label: 'Paper',    desc: 'Form-on-paper editorial fields',     icon: '□' },
  { id: 'pill',     label: 'Pill',     desc: 'Rounded search and filter fields',   icon: '◉' },
  { id: 'command',  label: 'Command',  desc: 'Palette-style stacked controls',     icon: '⌘' },
  { id: 'holo',     label: 'Holo',     desc: 'Cyan holographic glowing fields',    icon: '❋' },
  { id: 'crt',      label: 'CRT',      desc: 'Green phosphor monospace fields',    icon: '🖥' },
]

export const BUTTON_STYLES = [
  { id: 'cyber',    label: 'Cyber',    desc: 'Angular mono buttons, current default', icon: '⬡' },
  { id: 'pill',     label: 'Pill',     desc: 'Fully rounded soft buttons',            icon: '◉' },
  { id: 'brutal',   label: 'Brutalist', desc: 'Square, thick border, hard shadow',    icon: '■' },
  { id: 'ghost',    label: 'Ghost',    desc: 'Transparent, subtle bordered buttons',  icon: '◌' },
  { id: 'neon',     label: 'Neon',     desc: 'Glowing vivid buttons',                 icon: '✴' },
  { id: 'terminal', label: 'Terminal', desc: 'Square mono CLI buttons',               icon: '>_' },
  { id: 'minimal',  label: 'Minimal',  desc: 'Borderless quiet text buttons',         icon: '—' },
  { id: 'holo',     label: 'Holo',     desc: 'Holographic gradient-edge glow',        icon: '❋' },
]

export const CARD_STYLES = [
  { id: 'cyber',    label: 'Cyber',     desc: 'Current angular cards with accent bar', icon: '⬡' },
  { id: 'glass',    label: 'Glass',     desc: 'Frosted translucent blurred cards',     icon: '◻' },
  { id: 'brutal',   label: 'Brutalist', desc: 'Square hard-shadow blocks',             icon: '■' },
  { id: 'paper',    label: 'Paper',     desc: 'Warm editorial document cards',         icon: '□' },
  { id: 'minimal',  label: 'Minimal',   desc: 'Quiet cards, no accent bar',            icon: '—' },
  { id: 'neon',     label: 'Neon',      desc: 'Bright glowing bordered cards',         icon: '✴' },
  { id: 'terminal', label: 'Terminal',  desc: 'Phosphor CLI panels',                   icon: '>_' },
]

export const TABLE_STYLES = [
  { id: 'cyber',   label: 'Cyber',     desc: 'Current subtle row dividers',   icon: '⬡' },
  { id: 'minimal', label: 'Minimal',   desc: 'No borders, airy rows',         icon: '—' },
  { id: 'brutal',  label: 'Brutalist', desc: 'Full grid borders, hard edges', icon: '■' },
  { id: 'glass',   label: 'Glass',     desc: 'Translucent frosted rows',      icon: '◻' },
  { id: 'striped', label: 'Striped',   desc: 'Alternating row shading',       icon: '▤' },
]

export const BADGE_STYLES = [
  { id: 'pill',    label: 'Pill',      desc: 'Fully rounded, current default',   icon: '◉' },
  { id: 'square',  label: 'Square',    desc: 'Sharp 2px mono chips',             icon: '▣' },
  { id: 'neon',    label: 'Neon',      desc: 'Glowing vivid badges',             icon: '✴' },
  { id: 'minimal', label: 'Minimal',   desc: 'Plain text, no border',            icon: '—' },
  { id: 'brutal',  label: 'Brutalist', desc: 'Hard border with offset shadow',   icon: '■' },
]

export const SURFACE_STYLES = [
  { id: 'cyber-grid', label: 'Cyber Grid', desc: 'Current grid overlay and dark cards', icon: '▦' },
  { id: 'clean-app',  label: 'Clean App',  desc: 'Flat product surfaces, low glow',     icon: '□' },
  { id: 'glass-dock', label: 'Glass Dock', desc: 'Layered blur panels and light rims',  icon: '◻' },
  { id: 'paper-doc',  label: 'Paper Doc',  desc: 'Editorial page with section rules',   icon: '▤' },
  { id: 'terminal',   label: 'Terminal',   desc: 'CRT canvas with console panels',      icon: '>_' },
  { id: 'neon-stage', label: 'Neon Stage', desc: 'Dark stage with luminous strips',     icon: '✴' },
  { id: 'brutalist',  label: 'Brutalist',  desc: 'Hard edges, blocks, no blur',         icon: '■' },
  { id: 'dashboard',  label: 'Dashboard',  desc: 'Dense operations layout',             icon: '▥' },
  { id: 'holo',       label: 'Holo Deck',  desc: 'Layered holographic translucent panels', icon: '❋' },
  { id: 'void',       label: 'Void',       desc: 'Minimal near-black surfaces',         icon: '◐' },
]

export const LOADING_STYLES = [
  { id: 'terminal',   label: 'Terminal',   desc: 'Boot sequence'      },
  { id: 'minimal',    label: 'Minimal',    desc: 'Clean spinner'      },
  { id: 'glitch',     label: 'Glitch',     desc: 'Glitch text'        },
  { id: 'splash',     label: 'Splash',     desc: 'Brand reveal'       },
  { id: 'matrix',     label: 'Matrix',     desc: 'Matrix rain'        },
  { id: 'pulse',      label: 'Pulse',      desc: 'Breathing rings'    },
  { id: 'cyber',      label: 'Cyber',      desc: 'Hex grid boot'      },
  { id: 'bars',       label: 'Bars',       desc: 'Progress bars'      },
  { id: 'wave',       label: 'Wave',       desc: 'Wave sweep'         },
  { id: 'neon',       label: 'Neon',       desc: 'Neon flicker'       },
  { id: 'orbit',      label: 'Orbit',      desc: 'Animejs orbital'    },
  { id: 'typewriter', label: 'Typewriter', desc: 'Animejs char-by-char'},
  { id: 'dna',        label: 'DNA',        desc: 'Animejs helix'      },
  { id: 'countdown',  label: 'Countdown',  desc: 'Animejs 3-2-1-GO'   },
  { id: 'holo',       label: 'Holo',       desc: 'Holographic rings'  },
  { id: 'crt',        label: 'CRT',        desc: 'Green phosphor boot'},
]

export const ANIMATION_PRESETS = [
  { id: 'smooth',     label: 'Smooth',     desc: '0.35s elegant ease'    },
  { id: 'snappy',     label: 'Snappy',     desc: '0.12s fast and crisp'  },
  { id: 'bouncy',     label: 'Bouncy',     desc: '0.45s spring effect'   },
  { id: 'expressive', label: 'Expressive', desc: 'Bold, dramatic motion' },
  { id: 'reduced',    label: 'Reduced',    desc: 'Subtle, accessible'    },
  { id: 'elastic',    label: 'Elastic',    desc: 'Overshoot and snap'    },
  { id: 'cinematic',  label: 'Cinematic',  desc: 'Slow, dramatic ease'   },
  { id: 'none',       label: 'None',       desc: 'No animations at all'  },
]

export const NOTIFY_POSITIONS = [
  { id: 'bottom-right', label: 'Bottom Right', icon: '↘' },
  { id: 'bottom-left',  label: 'Bottom Left',  icon: '↙' },
  { id: 'top-right',    label: 'Top Right',    icon: '↗' },
  { id: 'top-left',     label: 'Top Left',     icon: '↖' },
  { id: 'top-center',   label: 'Top Center (Banner)', icon: '↑' },
]

export const THEME_PACKAGES = [
  {
    id: 'cyber-ops',
    name: 'Cyber Ops',
    mood: 'network command center',
    desc: 'Neon grid, tactical panels, scanline motion, and angular controls.',
    accent: '#00ff88',
    previewBg: '#060a0f',
    settings: {
      globalTheme: 'cyber-dark',
      headerStyle: 'cyber',
      footerStyle: 'cyber',
      menuStyle: 'cyber',
      notifyStyle: 'cyber',
      notifyPosition: 'bottom-right',
      dialogStyle: 'cyber',
      inputStyle: 'cyber',
      surfaceStyle: 'cyber-grid',
      buttonStyle: 'cyber',
      cardStyle: 'cyber',
      tableStyle: 'cyber',
      badgeStyle: 'neon',
      backgroundPattern: 'grid',
      gridPattern: 'grid',
      bgAnimation: 'none',
      loadingScreenStyle: 'cyber',
      animationPreset: 'smooth',
    },
  },
  {
    id: 'glass-console',
    name: 'Glass Console',
    mood: 'frosted operations desk',
    desc: 'Layered blur, floating menus, translucent inputs, and soft cinematic motion.',
    accent: '#00e5ff',
    previewBg: '#07111f',
    settings: {
      globalTheme: 'glass-dark',
      headerStyle: 'glass',
      footerStyle: 'glass',
      menuStyle: 'glass',
      notifyStyle: 'glass',
      notifyPosition: 'top-right',
      dialogStyle: 'glass',
      inputStyle: 'glass',
      surfaceStyle: 'glass-dock',
      buttonStyle: 'ghost',
      cardStyle: 'glass',
      tableStyle: 'glass',
      badgeStyle: 'pill',
      backgroundPattern: 'radial',
      gridPattern: 'radial',
      bgAnimation: 'none',
      loadingScreenStyle: 'pulse',
      animationPreset: 'cinematic',
    },
  },
  {
    id: 'editorial-paper',
    name: 'Editorial Paper',
    mood: 'magazine desk',
    desc: 'Warm paper surfaces, serif mastheads, document modals, and quiet inputs.',
    accent: '#c41a1a',
    previewBg: '#f4eadc',
    settings: {
      globalTheme: 'paper',
      headerStyle: 'editorial',
      footerStyle: 'paper',
      menuStyle: 'paper',
      notifyStyle: 'minimal',
      notifyPosition: 'top-center',
      dialogStyle: 'paper',
      inputStyle: 'paper',
      surfaceStyle: 'paper-doc',
      buttonStyle: 'pill',
      cardStyle: 'paper',
      tableStyle: 'minimal',
      badgeStyle: 'pill',
      backgroundPattern: 'clean',
      gridPattern: 'paper-doc',
      bgAnimation: 'none',
      loadingScreenStyle: 'minimal',
      animationPreset: 'reduced',
    },
  },
  {
    id: 'command-terminal',
    name: 'Command Terminal',
    mood: 'phosphor shell',
    desc: 'CLI chrome, phosphor fields, terminal dialogs, and fast command motion.',
    accent: '#33ff33',
    previewBg: '#050805',
    settings: {
      globalTheme: 'terminal',
      headerStyle: 'terminal',
      footerStyle: 'terminal',
      menuStyle: 'terminal',
      notifyStyle: 'terminal',
      notifyPosition: 'bottom-left',
      dialogStyle: 'terminal',
      inputStyle: 'terminal',
      surfaceStyle: 'terminal',
      buttonStyle: 'terminal',
      cardStyle: 'terminal',
      tableStyle: 'cyber',
      badgeStyle: 'square',
      backgroundPattern: 'scanlines',
      gridPattern: 'terminal',
      bgAnimation: 'none',
      loadingScreenStyle: 'terminal',
      animationPreset: 'snappy',
    },
  },
  {
    id: 'brutalist-system',
    name: 'Brutalist System',
    mood: 'hard-edged control panel',
    desc: 'Heavy borders, stark blocks, blunt dialogs, and no-softness UI.',
    accent: '#e8000d',
    previewBg: '#f2f0ec',
    settings: {
      globalTheme: 'brutalist',
      headerStyle: 'brutal',
      footerStyle: 'brutal',
      menuStyle: 'minimal',
      notifyStyle: 'glitch',
      notifyPosition: 'top-left',
      dialogStyle: 'brutal',
      inputStyle: 'brutal',
      surfaceStyle: 'brutalist',
      buttonStyle: 'brutal',
      cardStyle: 'brutal',
      tableStyle: 'brutal',
      badgeStyle: 'brutal',
      backgroundPattern: 'clean',
      gridPattern: 'clean',
      bgAnimation: 'none',
      loadingScreenStyle: 'bars',
      animationPreset: 'none',
    },
  },
  {
    id: 'arcade-neon',
    name: 'Arcade Neon',
    mood: 'retro neon cabinet',
    desc: 'Synthwave stage surfaces, chunky menus, bright alerts, and elastic motion.',
    accent: '#ff2d8b',
    previewBg: '#10071c',
    settings: {
      globalTheme: 'synthwave',
      headerStyle: 'neon-band',
      footerStyle: 'synthwave',
      menuStyle: 'arcade',
      notifyStyle: 'glitch',
      notifyPosition: 'bottom-right',
      dialogStyle: 'split',
      inputStyle: 'pill',
      surfaceStyle: 'neon-stage',
      buttonStyle: 'neon',
      cardStyle: 'neon',
      tableStyle: 'cyber',
      badgeStyle: 'neon',
      backgroundPattern: 'waves',
      gridPattern: 'neon-stage',
      bgAnimation: 'none',
      loadingScreenStyle: 'neon',
      animationPreset: 'elastic',
    },
  },
  {
    id: 'clean-saas',
    name: 'Clean SaaS',
    mood: 'calm product app',
    desc: 'Minimal header, clean app surface, simple forms, and restrained motion.',
    accent: '#0071e3',
    previewBg: '#f6f8fb',
    settings: {
      globalTheme: 'macos',
      headerStyle: 'minimal',
      footerStyle: 'minimal',
      menuStyle: 'minimal',
      notifyStyle: 'minimal',
      notifyPosition: 'top-right',
      dialogStyle: 'minimal',
      inputStyle: 'minimal',
      surfaceStyle: 'clean-app',
      buttonStyle: 'pill',
      cardStyle: 'minimal',
      tableStyle: 'minimal',
      badgeStyle: 'pill',
      backgroundPattern: 'clean',
      gridPattern: 'clean',
      bgAnimation: 'none',
      loadingScreenStyle: 'minimal',
      animationPreset: 'reduced',
    },
  },
  {
    id: 'dashboard-hud',
    name: 'Dashboard HUD',
    mood: 'dense system cockpit',
    desc: 'Operational header, drawer dialogs, telemetry toasts, and grid density.',
    accent: '#38bdf8',
    previewBg: '#07111a',
    settings: {
      globalTheme: 'ocean',
      headerStyle: 'dashboard',
      footerStyle: 'dashboard',
      menuStyle: 'rail',
      notifyStyle: 'hud',
      notifyPosition: 'top-right',
      dialogStyle: 'drawer',
      inputStyle: 'command',
      surfaceStyle: 'dashboard',
      buttonStyle: 'cyber',
      cardStyle: 'cyber',
      tableStyle: 'cyber',
      badgeStyle: 'square',
      backgroundPattern: 'circuit',
      gridPattern: 'dashboard',
      bgAnimation: 'none',
      loadingScreenStyle: 'bars',
      animationPreset: 'snappy',
    },
  },
  {
    id: 'holo-deck',
    name: 'Holo Deck',
    mood: 'holographic command surface',
    desc: 'Layered cyan glow, corner-bracketed dialogs, telemetry chips, and holo boot.',
    accent: '#00e5ff',
    previewBg: '#08121c',
    settings: {
      globalTheme: 'glass-dark',
      headerStyle: 'glass',
      footerStyle: 'glass',
      menuStyle: 'holo',
      notifyStyle: 'holo',
      notifyPosition: 'bottom-right',
      dialogStyle: 'holo',
      inputStyle: 'holo',
      surfaceStyle: 'holo',
      buttonStyle: 'holo',
      cardStyle: 'glass',
      tableStyle: 'glass',
      badgeStyle: 'pill',
      backgroundPattern: 'grid',
      gridPattern: 'radial',
      bgAnimation: 'none',
      loadingScreenStyle: 'holo',
      animationPreset: 'smooth',
    },
  },
  {
    id: 'phosphor-terminal',
    name: 'Phosphor CRT',
    mood: 'green phosphor mainframe',
    desc: 'CRT scanlines, matrix menus, phosphor fields, and a blink-cursor boot.',
    accent: '#33ff33',
    previewBg: '#020604',
    settings: {
      globalTheme: 'toxic',
      headerStyle: 'terminal',
      footerStyle: 'terminal',
      menuStyle: 'matrix',
      notifyStyle: 'chip',
      notifyPosition: 'bottom-left',
      dialogStyle: 'crt',
      inputStyle: 'crt',
      surfaceStyle: 'terminal',
      buttonStyle: 'terminal',
      cardStyle: 'terminal',
      tableStyle: 'cyber',
      badgeStyle: 'square',
      backgroundPattern: 'scanlines',
      gridPattern: 'terminal',
      bgAnimation: 'none',
      loadingScreenStyle: 'crt',
      animationPreset: 'snappy',
    },
  },
]

export const DEFAULT_FRAMEWORK = {
  menuStyle:      'cyber',
  notifyStyle:    'cyber',
  notifyPosition: 'bottom-right',
  dialogStyle:    'cyber',
  inputStyle:     'cyber',
  surfaceStyle:   'cyber-grid',
  buttonStyle:    'cyber',
  cardStyle:      'cyber',
  tableStyle:     'cyber',
  badgeStyle:     'pill',
  followOsTheme:  false,
}

// ── Per-theme UI personalities ─────────────────────────────────────────────
// Every VALID_THEMES id (core/themeCatalog.js) maps to its menu / dialog /
// input / surface / notify / button / card / table / badge style ids. Colors
// & fonts are untouched — only the siteConfig framework keys (menuStyle,
// dialogStyle, inputStyle, surfaceStyle, notifyStyle, buttonStyle, cardStyle,
// tableStyle, badgeStyle) follow the theme's vibe. Only ids from the
// MENU_/DIALOG_/INPUT_/SURFACE_/NOTIFY_/BUTTON_/CARD_/TABLE_/BADGE_STYLES
// vocabularies above are used.
export const THEME_FRAMEWORK = {
  'cyber-dark':     { menu: 'cyber',    dialog: 'cyber',    input: 'cyber',    surface: 'cyber-grid', notify: 'chip',   button: 'cyber',    card: 'cyber',    table: 'cyber',   badge: 'neon'   },
  'cyber-light':    { menu: 'minimal',  dialog: 'sheet',    input: 'minimal',  surface: 'clean-app',  notify: 'chip',   button: 'cyber',    card: 'cyber',    table: 'minimal', badge: 'neon'   },
  'light':          { menu: 'minimal',  dialog: 'sheet',    input: 'minimal',  surface: 'clean-app',  notify: 'chip',   button: 'pill',     card: 'minimal',  table: 'minimal', badge: 'pill'   },
  'midnight':       { menu: 'command',  dialog: 'split',    input: 'command',  surface: 'dashboard',  notify: 'inbox',  button: 'cyber',    card: 'cyber',    table: 'cyber',   badge: 'pill'   },
  'midnight-light': { menu: 'command',  dialog: 'split',    input: 'command',  surface: 'dashboard',  notify: 'inbox',  button: 'cyber',    card: 'cyber',    table: 'minimal', badge: 'pill'   },
  'crimson':        { menu: 'command',  dialog: 'drawer',   input: 'command',  surface: 'dashboard',  notify: 'banner', button: 'cyber',    card: 'cyber',    table: 'cyber',   badge: 'pill'   },
  'crimson-light':  { menu: 'command',  dialog: 'drawer',   input: 'command',  surface: 'dashboard',  notify: 'banner', button: 'cyber',    card: 'cyber',    table: 'minimal', badge: 'pill'   },
  'ocean':          { menu: 'glass',    dialog: 'drawer',   input: 'glass',    surface: 'glass-dock', notify: 'float',  button: 'ghost',    card: 'glass',    table: 'glass',   badge: 'pill'   },
  'ocean-light':    { menu: 'glass',    dialog: 'drawer',   input: 'glass',    surface: 'glass-dock', notify: 'float',  button: 'ghost',    card: 'glass',    table: 'glass',   badge: 'pill'   },
  'amber':          { menu: 'rail',     dialog: 'sheet',    input: 'pill',     surface: 'dashboard',  notify: 'chip',   button: 'pill',     card: 'cyber',    table: 'cyber',   badge: 'pill'   },
  'amber-light':    { menu: 'rail',     dialog: 'sheet',    input: 'pill',     surface: 'dashboard',  notify: 'chip',   button: 'pill',     card: 'cyber',    table: 'minimal', badge: 'pill'   },
  'rose':           { menu: 'floating', dialog: 'sheet',    input: 'pill',     surface: 'clean-app',  notify: 'float',  button: 'pill',     card: 'minimal',  table: 'minimal', badge: 'pill'   },
  'rose-light':     { menu: 'floating', dialog: 'sheet',    input: 'pill',     surface: 'clean-app',  notify: 'float',  button: 'pill',     card: 'minimal',  table: 'minimal', badge: 'pill'   },
  'forest':         { menu: 'command',  dialog: 'drawer',   input: 'minimal',  surface: 'dashboard',  notify: 'inbox',  button: 'cyber',    card: 'cyber',    table: 'cyber',   badge: 'pill'   },
  'forest-light':   { menu: 'command',  dialog: 'drawer',   input: 'minimal',  surface: 'dashboard',  notify: 'inbox',  button: 'cyber',    card: 'cyber',    table: 'minimal', badge: 'pill'   },
  'lava':           { menu: 'neon',     dialog: 'drawer',   input: 'brutal',   surface: 'neon-stage', notify: 'banner', button: 'neon',     card: 'neon',     table: 'cyber',   badge: 'neon'   },
  'lava-light':     { menu: 'neon',     dialog: 'drawer',   input: 'brutal',   surface: 'neon-stage', notify: 'banner', button: 'neon',     card: 'neon',     table: 'minimal', badge: 'neon'   },
  'toxic':          { menu: 'matrix',   dialog: 'split',    input: 'crt',      surface: 'terminal',   notify: 'hud',    button: 'neon',     card: 'terminal', table: 'cyber',   badge: 'neon'   },
  'toxic-light':    { menu: 'matrix',   dialog: 'split',    input: 'crt',      surface: 'terminal',   notify: 'hud',    button: 'neon',     card: 'terminal', table: 'minimal', badge: 'neon'   },
  'ice':            { menu: 'glass',    dialog: 'sheet',    input: 'pill',     surface: 'clean-app',  notify: 'banner', button: 'pill',     card: 'minimal',  table: 'minimal', badge: 'pill'   },
  'glass-dark':     { menu: 'glass',    dialog: 'glass',    input: 'glass',    surface: 'glass-dock', notify: 'glass',  button: 'ghost',    card: 'glass',    table: 'glass',   badge: 'pill'   },
  'glass-light':    { menu: 'glass',    dialog: 'glass',    input: 'glass',    surface: 'glass-dock', notify: 'glass',  button: 'ghost',    card: 'glass',    table: 'glass',   badge: 'pill'   },
  'brutalist':      { menu: 'rail',     dialog: 'brutal',   input: 'brutal',   surface: 'brutalist',  notify: 'chip',   button: 'brutal',   card: 'brutal',   table: 'brutal',  badge: 'brutal' },
  'brutalist-dark': { menu: 'rail',     dialog: 'brutal',   input: 'brutal',   surface: 'brutalist',  notify: 'chip',   button: 'brutal',   card: 'brutal',   table: 'brutal',  badge: 'brutal' },
  'synthwave':      { menu: 'neon',     dialog: 'split',    input: 'crt',      surface: 'neon-stage', notify: 'glitch', button: 'neon',     card: 'neon',     table: 'cyber',   badge: 'neon'   },
  'synthwave-light':{ menu: 'neon',     dialog: 'split',    input: 'crt',      surface: 'neon-stage', notify: 'glitch', button: 'neon',     card: 'neon',     table: 'minimal', badge: 'neon'   },
  'paper':          { menu: 'paper',    dialog: 'paper',    input: 'paper',    surface: 'paper-doc',  notify: 'minimal',button: 'pill',     card: 'paper',    table: 'minimal', badge: 'pill'   },
  'paper-dark':     { menu: 'paper',    dialog: 'paper',    input: 'paper',    surface: 'paper-doc',  notify: 'minimal',button: 'pill',     card: 'paper',    table: 'minimal', badge: 'pill'   },
  'neumorph':       { menu: 'floating', dialog: 'sheet',    input: 'pill',     surface: 'clean-app',  notify: 'float',  button: 'minimal',  card: 'minimal',  table: 'minimal', badge: 'pill'   },
  'neumorph-dark':  { menu: 'floating', dialog: 'sheet',    input: 'pill',     surface: 'clean-app',  notify: 'float',  button: 'minimal',  card: 'minimal',  table: 'minimal', badge: 'pill'   },
  'terminal':       { menu: 'terminal', dialog: 'terminal', input: 'terminal', surface: 'terminal',   notify: 'terminal', button: 'terminal', card: 'terminal', table: 'cyber', badge: 'square' },
  'terminal-light': { menu: 'terminal', dialog: 'terminal', input: 'terminal', surface: 'terminal',   notify: 'terminal', button: 'terminal', card: 'terminal', table: 'minimal', badge: 'square' },
  'macos':          { menu: 'floating', dialog: 'sheet',    input: 'pill',     surface: 'clean-app',  notify: 'banner', button: 'pill',     card: 'minimal',  table: 'minimal', badge: 'pill'   },
  'macos-dark':     { menu: 'floating', dialog: 'sheet',    input: 'pill',     surface: 'clean-app',  notify: 'banner', button: 'pill',     card: 'minimal',  table: 'minimal', badge: 'pill'   },
  'neon-noir':      { menu: 'neon',     dialog: 'drawer',   input: 'minimal',  surface: 'neon-stage', notify: 'hud',    button: 'neon',     card: 'neon',     table: 'cyber',   badge: 'neon'   },
  'neon-noir-light':{ menu: 'neon',     dialog: 'drawer',   input: 'minimal',  surface: 'neon-stage', notify: 'hud',    button: 'neon',     card: 'neon',     table: 'minimal', badge: 'neon'   },
  'pastel':         { menu: 'floating', dialog: 'sheet',    input: 'pill',     surface: 'clean-app',  notify: 'float',  button: 'minimal',  card: 'minimal',  table: 'minimal', badge: 'pill'   },
  'pastel-dark':    { menu: 'floating', dialog: 'sheet',    input: 'pill',     surface: 'clean-app',  notify: 'float',  button: 'minimal',  card: 'minimal',  table: 'minimal', badge: 'pill'   },
  'win95':          { menu: 'rail',     dialog: 'sheet',    input: 'minimal',  surface: 'clean-app',  notify: 'chip',   button: 'brutal',   card: 'brutal',   table: 'brutal',  badge: 'square' },
  'win95-dark':     { menu: 'rail',     dialog: 'sheet',    input: 'minimal',  surface: 'clean-app',  notify: 'chip',   button: 'brutal',   card: 'brutal',   table: 'brutal',  badge: 'square' },
  'aurora':         { menu: 'holo',     dialog: 'drawer',   input: 'holo',     surface: 'holo',       notify: 'chip',   button: 'holo',     card: 'glass',    table: 'glass',   badge: 'pill'   },
  'aurora-light':   { menu: 'holo',     dialog: 'drawer',   input: 'holo',     surface: 'holo',       notify: 'chip',   button: 'holo',     card: 'glass',    table: 'glass',   badge: 'pill'   },
  'ember-dark':     { menu: 'command',  dialog: 'split',    input: 'command',  surface: 'dashboard',  notify: 'banner', button: 'cyber',    card: 'cyber',    table: 'cyber',   badge: 'pill'   },
  'ember-light':    { menu: 'command',  dialog: 'split',    input: 'command',  surface: 'dashboard',  notify: 'banner', button: 'cyber',    card: 'cyber',    table: 'minimal', badge: 'pill'   },
  'cobalt-dark':    { menu: 'command',  dialog: 'drawer',   input: 'command',  surface: 'dashboard',  notify: 'hud',    button: 'cyber',    card: 'cyber',    table: 'cyber',   badge: 'pill'   },
  'cobalt-light':   { menu: 'command',  dialog: 'drawer',   input: 'command',  surface: 'dashboard',  notify: 'hud',    button: 'cyber',    card: 'cyber',    table: 'minimal', badge: 'pill'   },
  'slate-dark':     { menu: 'minimal',  dialog: 'sheet',    input: 'minimal',  surface: 'clean-app',  notify: 'chip',   button: 'cyber',    card: 'cyber',    table: 'cyber',   badge: 'square' },
  'slate-light':    { menu: 'minimal',  dialog: 'sheet',    input: 'minimal',  surface: 'clean-app',  notify: 'chip',   button: 'cyber',    card: 'cyber',    table: 'minimal', badge: 'square' },
  'honey-dark':     { menu: 'rail',     dialog: 'sheet',    input: 'pill',     surface: 'dashboard',  notify: 'inbox',  button: 'pill',     card: 'cyber',    table: 'cyber',   badge: 'pill'   },
  'honey-light':    { menu: 'rail',     dialog: 'sheet',    input: 'pill',     surface: 'dashboard',  notify: 'inbox',  button: 'pill',     card: 'cyber',    table: 'minimal', badge: 'pill'   },
  'violet-dark':    { menu: 'floating', dialog: 'split',    input: 'pill',     surface: 'clean-app',  notify: 'float',  button: 'pill',     card: 'glass',    table: 'cyber',   badge: 'pill'   },
  'violet-light':   { menu: 'floating', dialog: 'split',    input: 'pill',     surface: 'clean-app',  notify: 'float',  button: 'pill',     card: 'glass',    table: 'minimal', badge: 'pill'   },
  'teal-dark':      { menu: 'glass',    dialog: 'drawer',   input: 'glass',    surface: 'glass-dock', notify: 'float',  button: 'ghost',    card: 'glass',    table: 'glass',   badge: 'pill'   },
  'teal-light':     { menu: 'glass',    dialog: 'drawer',   input: 'glass',    surface: 'glass-dock', notify: 'float',  button: 'ghost',    card: 'glass',    table: 'glass',   badge: 'pill'   },
  'mario':          { menu: 'arcade',   dialog: 'drawer',   input: 'brutal',   surface: 'brutalist',  notify: 'banner', button: 'brutal',   card: 'brutal',   table: 'cyber',   badge: 'brutal' },
  'mario-light':    { menu: 'arcade',   dialog: 'drawer',   input: 'brutal',   surface: 'brutalist',  notify: 'banner', button: 'brutal',   card: 'brutal',   table: 'minimal', badge: 'brutal' },
  'minecraft':      { menu: 'arcade',   dialog: 'drawer',   input: 'brutal',   surface: 'brutalist',  notify: 'banner', button: 'brutal',   card: 'brutal',   table: 'brutal',  badge: 'square' },
  'minecraft-light':{ menu: 'arcade',   dialog: 'drawer',   input: 'brutal',   surface: 'brutalist',  notify: 'banner', button: 'brutal',   card: 'brutal',   table: 'brutal',  badge: 'square' },
  'sonic':          { menu: 'arcade',   dialog: 'drawer',   input: 'brutal',   surface: 'brutalist',  notify: 'banner', button: 'pill',     card: 'neon',     table: 'cyber',   badge: 'neon'   },
  'sonic-light':    { menu: 'arcade',   dialog: 'drawer',   input: 'brutal',   surface: 'brutalist',  notify: 'banner', button: 'pill',     card: 'neon',     table: 'minimal', badge: 'neon'   },
  'pacman':         { menu: 'arcade',   dialog: 'split',    input: 'crt',      surface: 'neon-stage', notify: 'glitch', button: 'neon',     card: 'neon',     table: 'cyber',   badge: 'neon'   },
  'pacman-light':   { menu: 'arcade',   dialog: 'split',    input: 'crt',      surface: 'neon-stage', notify: 'glitch', button: 'neon',     card: 'neon',     table: 'minimal', badge: 'neon'   },
  'dracula':        { menu: 'command',  dialog: 'split',    input: 'command',  surface: 'dashboard',  notify: 'banner', button: 'pill',     card: 'glass',    table: 'cyber',   badge: 'pill'   },
  'nord':           { menu: 'minimal',  dialog: 'sheet',    input: 'minimal',  surface: 'clean-app',  notify: 'chip',   button: 'cyber',    card: 'cyber',    table: 'cyber',   badge: 'square' },
  'tokyo-night':    { menu: 'neon',     dialog: 'drawer',   input: 'crt',      surface: 'neon-stage', notify: 'hud',    button: 'pill',     card: 'glass',    table: 'cyber',   badge: 'pill'   },
  'gruvbox':        { menu: 'terminal', dialog: 'sheet',    input: 'terminal', surface: 'terminal',   notify: 'inbox',  button: 'terminal', card: 'terminal', table: 'cyber',   badge: 'square' },
  'solarized-dark': { menu: 'command',  dialog: 'split',    input: 'command',  surface: 'dashboard',  notify: 'chip',   button: 'terminal', card: 'terminal', table: 'cyber',   badge: 'square' },
  'monokai':        { menu: 'matrix',   dialog: 'drawer',   input: 'crt',      surface: 'terminal',   notify: 'glitch', button: 'terminal', card: 'terminal', table: 'cyber',   badge: 'square' },
  'catppuccin':     { menu: 'floating', dialog: 'split',    input: 'pill',     surface: 'clean-app',  notify: 'float',  button: 'pill',     card: 'glass',    table: 'cyber',   badge: 'pill'   },
  'one-dark':       { menu: 'minimal',  dialog: 'drawer',   input: 'minimal',  surface: 'dashboard',  notify: 'chip',   button: 'cyber',    card: 'cyber',    table: 'cyber',   badge: 'neon'   },
}

// Resolve a theme's personality into siteConfig framework keys via write().
// Unmapped ids are left untouched (defensive — never clobbers explicit config).
export function applyThemeFramework(id, write) {
  const entry = THEME_FRAMEWORK[id]
  if (!entry || typeof write !== 'function') return false
  if (entry.menu)    write('menuStyle', entry.menu)
  if (entry.dialog)  write('dialogStyle', entry.dialog)
  if (entry.input)   write('inputStyle', entry.input)
  if (entry.surface) write('surfaceStyle', entry.surface)
  if (entry.notify)  write('notifyStyle', entry.notify)
  if (entry.button)  write('buttonStyle', entry.button)
  if (entry.card)    write('cardStyle', entry.card)
  if (entry.table)   write('tableStyle', entry.table)
  if (entry.badge)   write('badgeStyle', entry.badge)
  return true
}

// Loading screen & animation preset are site-wide settings managed in
// Theme Library → ⚙ Global Settings (not per-component framework choices).
export const FRAMEWORK_CATEGORIES = [
  { id: 'menu',   label: 'Menu Style',    icon: '☰',  color: '#a78bfa', styles: MENU_STYLES,   configKey: 'menuStyle'   },
  { id: 'notify', label: 'Notifications', icon: '🔔', color: '#ff6b35', styles: NOTIFY_STYLES,  configKey: 'notifyStyle' },
  { id: 'dialog', label: 'Dialogs',       icon: '💬', color: '#ffd700', styles: DIALOG_STYLES,  configKey: 'dialogStyle' },
  { id: 'input',  label: 'Inputs',        icon: '⌨',  color: '#38bdf8', styles: INPUT_STYLES,   configKey: 'inputStyle'  },
  { id: 'surface', label: 'Surfaces',     icon: '▧',  color: '#34d399', styles: SURFACE_STYLES, configKey: 'surfaceStyle' },
  { id: 'button', label: 'Buttons',      icon: '🔘', color: '#4ade80', styles: BUTTON_STYLES,  configKey: 'buttonStyle'  },
  { id: 'card',   label: 'Cards',        icon: '🃏', color: '#f472b6', styles: CARD_STYLES,    configKey: 'cardStyle'    },
  { id: 'table',  label: 'Tables',       icon: '▦',  color: '#22d3ee', styles: TABLE_STYLES,   configKey: 'tableStyle'   },
  { id: 'badge',  label: 'Badges',       icon: '🏷', color: '#facc15', styles: BADGE_STYLES,   configKey: 'badgeStyle'   },
]
