"""
routers/__init__.py — Main router registry

Routers are mounted directly in main.py. This module only keeps
back-compat imports so `from routers import X` still works.
"""

# Back-compat: direct router imports still work
from . import (
    admin_actions,
    audit,
    auth,
    backup,
    banners,
    blog,
    cdn_settings,
    chat,
    chat_admin,
    chat_ai,
    chat_dm,
    chat_livekit,
    chat_url_preview,
    contact,
    content,
    content_aggregator,
    cron,
    db_console,
    discord_auth,
    documents,
    email_settings,
    file_tools,
    fivem,
    forms,
    github_auth,
    helpdesk,
    mail_queue,
    mail_templates,
    mobile_admin,
    mobile_release,
    monitor,
    network,
    notifications,
    pdf_editor,
    portfolio,
    search,
    seo_proxy,
    site_settings,
    sitemap,
    stats,
    steam_auth,
    store,
    store_admin,
    store_catalog_admin,
    store_crm_admin,
    store_delivery,
    store_ecommerce,
    store_inventory,
    store_inventory_admin,
    store_ledger,
    store_marketing_admin,
    store_terminal_admin,
    txadmin_webhook,
    upload,
    vpn,
    webhooks,
)
